# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mahjong

class Suit(object):
    BAMBOO = 0
    CHARACTER = 1
    DOT = 2
    WINDS = 3
    DRAGONS = 4
    FLOWERS = 5
    SEASONS = 6
